### ISSUE TITLE
testing "Perform Path-Based UE Traffic Assignment using the Python Column-Generation Module"

### ISSUE THREAD

**Issue by YuanzhengLei** [jdlph/Path4GMNS#20]
TypeError: '>' not supported between instances of 'str' and 'float'.  817 line classes.py
[zone.csv](https://github.com/jdlph/Path4GMNS/files/9608446/zone.csv)
[demand.csv](https://github.com/jdlph/Path4GMNS/files/9608449/demand.csv)
[link.csv](https://github.com/jdlph/Path4GMNS/files/9608450/link.csv)
[node.csv](https://github.com/jdlph/Path4GMNS/files/9608453/node.csv)
primal code:
"
import path4gmns as pg
from time import time
network = pg.read_network(load_demand=False)
#network = pg.read_network()
column_gen_num = 20
column_update_num = 10
# path-based UE only
pg.perform_column_generation(column_gen_num, column_update_num, network)
# if you do not want to include geometry info in the output file,
# use pg.output_columns(network, False)
pg.output_columns(network)
pg.output_link_performance(network)
"
error:
"
path4gmns, version 0.8.5
read node.csv
the number of nodes is 357
the number of zones is 0
read link.csv
the number of links is 646
current iteration number in column generation: 0
Traceback (most recent call last):
  File "C:\Users\Yuanzheng Edison Lei\PycharmProjects\testGMNS\main.py", line 8, in <module>
    pg.perform_column_generation(column_gen_num, column_update_num, network)
  File "C:\Users\Yuanzheng Edison Lei\PycharmProjects\testGMNS\venv\lib\site-packages\path4gmns\colgen.py", line 337, in perform_column_generation
    _update_link_travel_time_and_cost(links, dps, i)
  File "C:\Users\Yuanzheng Edison Lei\PycharmProjects\testGMNS\venv\lib\site-packages\path4gmns\colgen.py", line 30, in _update_link_travel_time_and_cost
    link.calculate_td_vdf(demand_periods, iter_num)
  File "C:\Users\Yuanzheng Edison Lei\PycharmProjects\testGMNS\venv\lib\site-packages\path4gmns\classes.py", line 175, in calculate_td_vdf
    self.vdfperiods[tau].run_bpr(self.flow_vol_by_period[tau],
  File "C:\Users\Yuanzheng Edison Lei\PycharmProjects\testGMNS\venv\lib\site-packages\path4gmns\classes.py", line 818, in run_bpr
    self.voc = vol / max(SMALL_DIVISOR, self.capacity * reduction_ratio)
TypeError: '>' not supported between instances of 'str' and 'float'

Process finished with exit code 1
"

**Comment by jdlph** [comment]
Thank you for submitting an issue! Please include more details for us to replicate this issue, such as the version number, a complete error output from the terminal, and the data set.

**Comment by jdlph** [comment]
It is due to empty records of VDF_cap1 in link.csv. The parser returns an empty string to each VDF_cap which later will be passed to the column generation module when updating link travel time using BRP. It has been fixed under commit 71c019e51be1170b52c36887eba061a9acc93f24 and further enhanced under commits a1b67ae1d5f728294978f9bf4bb7898fc45ce5cf, 8a73f1f135a0ccdd3fa65fbca6ca407d9182e35c, and 5bb90a23020298934f0e43da7b9ca94fe72ed234.

They will be part of our next release as v0.8.6. If you want to test them out before release, you can follow the instruction [here](https://github.com/jdlph/Path4GMNS/tree/dev#2-build-and-install-the-python-package) to build Path4GMNS from source using the latest source code from [branch dev](https://github.com/jdlph/Path4GMNS/tree/dev).

Thank you again for helping us improve this repo!!
