### ISSUE TITLE
Issue in perform Path-Based UE Traffic Assignment

### ISSUE THREAD

**Issue by YuanzhengLei** [jdlph/Path4GMNS#23]
I can only use the function load_demand() to load demand instead of the function read_network(load_demand = True) shown in the tutorial.
```python
network = pg.read_network()
pg.read_zones(network)
pg.load_demand(network)

column_gen_num = 20
column_update_num = 10

# path-based UE only
pg.perform_column_generation(column_gen_num, column_update_num, network)

# if you do not want to include geometry info in the output file,
# use pg.output_columns(network, False)
pg.output_columns(network)
pg.output_link_performance(network)
```
![image](https://user-images.githubusercontent.com/113956766/193482555-b5e50f42-b177-4d2b-87da-e2525a6761d8.png)
```python
network = pg.read_network(load_demand=True)

column_gen_num = 20
column_update_num = 10

# path-based UE only
pg.perform_column_generation(column_gen_num, column_update_num, network)

# if you do not want to include geometry info in the output file,
# use pg.output_columns(network, False)
pg.output_columns(network)
pg.output_link_performance(network)
```
![image](https://user-images.githubusercontent.com/113956766/193482594-3abaec32-e5ca-42f1-b0a5-e8b6326172bd.png)

[zone.csv](https://github.com/jdlph/Path4GMNS/files/9693856/zone.csv)
[node.csv](https://github.com/jdlph/Path4GMNS/files/9693857/node.csv)
[link.csv](https://github.com/jdlph/Path4GMNS/files/9693858/link.csv)
[demand.csv](https://github.com/jdlph/Path4GMNS/files/9693859/demand.csv)

**Comment by jdlph** [comment]
Thank you for reporting!  You encountered this exception as there is no zone information in your node.csv. This caveat has been clearly documented in the tutorial.

"**Note that** read_network(load_demand=True) will **automatically check OD connectivity** which **requires zone info to be specified in node.csv**. Otherwise, you will get an exception stating _NO VALID OD VOLUME!! DOUBLE CHECK YOUR demand.csv_'"
