### ISSUE TITLE
Problem with travel time

### ISSUE THREAD

**Issue by zahranmdi** [jdlph/Path4GMNS#29]
I ran the code and I filled length and speed columns in link.csv, but in the link_performance.csv file I get the travel_time exactly same as length. How can I address this issue?

**Comment by jdlph** [comment]
Thank you for submitting an issue! Please provide the following information so that we can replicate this issue.

1. Input files and settings.yml.
2. Version of Path4GMNS (e.g., v0.9.1, which will be output from the console each time you run it) you used and the function you called.

You can attach files directly along this thread.

**Comment by jdlph** [comment]
This issue is closed as no response was received. The specific free flow speed value (e.g., 60 mph, which makes the length and the free travel time the same number) and the extremely high link capacity (i.e., 49,500, which makes the travel time almost close to the free flow travel time under a reasonable traffic load) is highly likely to be the reason.
