### ISSUE TITLE
read user defined agent types in allowed_uses

### ISSUE THREAD

**Issue by asu-trans-ai-lab** [jdlph/Path4GMNS#4]
The current implementation seems to be limited to walk and bike in field allowed_uses in link.csv. A user can specify agent type = n in settings.cv, and define agent types flexibly for multimodal planning. Test network is attached. 
[4_stops_example.zip](https://github.com/jdlph/Path4GMNS/files/6519402/4_stops_example.zip)

**Comment by jdlph** [comment]
It has been fixed in v0.7.2 and tested using the sample network you provided. Note that any new demand_periods shall be appended under "demand_periods: in settings.yaml. Creating "demand_periods_1" and anything similar is not supported, and will lead to an exception to be thrown.

Thank you for reporting this issue!!
