### ISSUE TITLE
tutorial.ipynb

### ISSUE THREAD

**Issue by rkn2** [jdlph/Path4GMNS#42]
based on a previous reply, I edited my node.csv and link.csv so that the ids are floats in both and I also used path4gmns==0.9.4. This got me through the first issue and i get the following warning output from 3.1 
<img width="1283" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/e2044eb5-7f84-4d23-8f18-3b7598585cb1">
Next I tried two things: 
1) Since I already have a demand.csv and zone.csv from running grid2demand, I ran 3.2 directly from 3.0 with these demand.csv and zone.csv
[zone.csv](https://github.com/jdlph/Path4GMNS/files/12587459/zone.csv)
[demand.csv](https://github.com/jdlph/Path4GMNS/files/12587460/demand.csv)
and I got this error: 
<img width="992" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/58fd1834-3256-44b7-926a-c6ca57b3befd">

2) To see if my issue was stemming from files with grid2demand, I deleted my demand.csv and zone.csv files and ran section 3.2 to create them.
That created these demand.csv and zone.csv 
[zone_from tutorial.csv](https://github.com/jdlph/Path4GMNS/files/12587442/zone_from.tutorial.csv)
[demand_from tutorial.csv](https://github.com/jdlph/Path4GMNS/files/12587443/demand_from.tutorial.csv)
and yielded this error in the next block of code: 
<img width="1237" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/2b59aecd-dc34-418d-98ad-444857775c0b">

I am not sure if these issues stem from downgrading to 0.9.4 or if there is another problem with my data. thanks for your help!

**Comment by jdlph** [comment]
Those warnings and exceptions are not errors of Path4GMNS. They are part of the internal validation which indicate what went wrong with the input data and what the possible fixes are.

Take the first two warnings for example, Path4GMNS warns you that **settings.yml is missing**, and it will set up the run using the default values for demand period and agent type. You can find details on settings.yml in the [tutorial](https://github.com/jdlph/Path4GMNS/blob/dev/tests/tutorial.ipynb) under session 4.1 and in the [Use Cases](https://path4gmns.readthedocs.io/en/latest/usecases.html#evaluate-multimodal-accessibility).

Then the next one (i.e., KeyError: 'zone_id') informs you that the column of **zone_id** is missing from zone.csv. There is a column with header **activity_zone_id** rather than **zone_id** in your zone file.

The last one is related to **the length unit of links**. As mentioned in the tutorial, Path4GMNS uses **mile** and **mile per hour (mph)** as the default units for length and speed in its internal calculation and all outputs. Links presented in your link.csv have large values in length, which do not make sense if mile is the unit. 

As the demand synthesis is subjected to a time budget (the default value is 120 min), no OD pairs are connected / reachable given this time budget and no demand is synthesized (see [Synthesize Zones and OD Demand](https://path4gmns.readthedocs.io/en/latest/usecases.html#synthesize-zones-and-od-demand) for details). Therefore, you got the last warning from Path4GMNS (i.e., "NO VALID OD VOLUME!! Double check your demand.csv and make sure there is zone info in node.csv'") as your [demand_from tutorial.csv](https://github.com/jdlph/Path4GMNS/files/12587443/demand_from.tutorial.csv) is empty. 

You can get around this issue by specifying the length unit as meter (or bump up the time budget to a very large number). 

<img width="852" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/31260633/17ab240f-e065-47dc-93d5-2b8c9e3d674e">
